[target.x86_64-unknown-none]
runner = "qemu-system-x86_64 -drive format=raw,file=target/x86_64-unknown-none/debug/hyperml_v1 -s -S"
rustflags = [
  "-C", "link-arg=-Tlink.ld",
  "-C", "relocation-model=static",
  "-C", "target-feature=+crt-static",
]